### ISSUE TITLE
Push edits on the akshay-fluent-physics branch.

### ISSUE THREAD

**Issue by akshaybbagi** [sfo-project/2D-flow-over-rotating-cylinder-laminar#2]
I have made modifications to the Physics file and saved it. I added it and committed it. When I try to push it to the branch - "akshay-fluent-physics" I get this error:

error: src refspec akshay-fluent-physics does not match any.
error: failed to push some refs to 'https://github.com/sfo-project/2D-flow-over-rotating-cylinder-laminar.git'

I tried several times but couldn't figure out what went wrong. I ended up trying pushing on master branch and it worked! Maybe that was not the best approach, but please help with this issue.

**Comment by ardeshirj** [comment]
Can you provide the full command you used to push to the branch?

**Comment by akshaybbagi** [comment]
git push origin akshay-fluent-physics

**Comment by ardeshirj** [comment]
It was not clear what caused this issue, and the alternative option was to create a separate branch.
